# Generated by Django 4.2.1 on 2023-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdb',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='img',
            field=models.ImageField(default='', upload_to='./holdApi/images/', verbose_name='Label'),
        ),
    ]
